// AUTO-GENERATED by electron/scripts/generate-build-mode.js — do not edit by hand.
// Derived from src/environments/_environment.prod.ts (`mode`) or the APP_MODE env var.
export const BUILD_MODE: 'prod' | 'dev' | 'stg' = 'stg';

// Auto-update is only active in production builds. stg/dev builds ship without it.
export const AUTO_UPDATE_ENABLED = false;
