#Mon Mar 23 13:06:57 IST 2026
BASE_URL_DEVELOPMENT=https\://uni-ooi-giga-meter-backend-dev.azurewebsites.net/api/v1/
BASE_URL_PRODUCTION=https\://uni-ooi-giga-meter-backend.azurewebsites.net/api/v1/
BASE_URL_STAGING=https\://uni-ooi-giga-meter-backend-stg.azurewebsites.net/api/v1/
KEYSTORE_PASSWORD=GigaMeter
KEYSTORE_PATH=unicef_keystore.jks
KEY_ALIAS=mykey
KEY_PASSWORD=GigaMeter
VERSION_CODE=34
VERSION_NAME=1.1.34
android.useAndroidX=true
org.gradle.jvmargs=-Xmx1536m
